
server:
  port: 8099
spring:
  rabbitmq:
    host: 192.168.0.138
    port: 5672
    username: zhongxia
    password: zhongxia
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual #手动ACK 不开启自动ACK模式,目的是防止报错后未正确处理消息丢失 默认 为 none