
server:
  port: 8099
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jx_temp?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: root
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zgs.domain
  configuration:
    map-underscore-to-camel-case: true
